service: app

frameworkVersion: '3'



plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  region: ${file(./variables.json):AWSREGION}
  stage: ${file(./variables.json):AWSSTAGE}

  memorySize: 1024
  timeout: 30

  iam:
    role:
      managedPolicies:
      - arn:aws:iam:aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam:aws:policy/AmazonS3FullAccess

functions:
  - HelloWorldFunction:
      handler: src/app.lambda_handler
      events:
        - http:
            path: helloworld
            cors: true
            method: get

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: ${self:service}-${self:provider.stage}-python-libraries
      description: "Layer with libraries"
      compatibleRuntimes:
        - python3.9
