name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  python-env:
    name: python-env
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
  test:
    name: test
    runs-on: ubuntu-18.04
    needs: python-env
    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: |
          pip install pytest
          pytest ./unit
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: npm ci
      - run: npm install
      - name: Serverless Deploy
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS-STAGE: dev