name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  python-env:
    name: python-env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
        exclude:
          - os: macos-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.6'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
  test:
    name: test
    needs: python-env
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: |
          pip install pytest
          pytest unit
  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
