name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    uses: ./.github/workflow/build.yml
    with:
      stage: dev
    steps:
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest unit
  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
