name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  python-env:
    name: python-env
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
  test:
    name: test
    runs-on: ubuntu-18.04
    needs: python-env
    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: |
          pip install pytest
          pytest ./unit
  build-deploy:
    name: build-deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --region sa-east-1 --stack-name app --no-confirm-changeset --no-fail-on-empty-changeset --s3-bucket "app-bucket" --capabilities CAPABILITY_IAM --parameter-overrides Environment="dev"
